# Copyright 2026 Aayush Chawla
# SPDX-License-Identifier: Apache-2.0

"""MCP server HTTP/SSE transport + management API.

External MCP clients (Claude Desktop, Cursor, VS Code) and the in-app Claude
Code coding-agent spawner both connect to `/mcp/sse` here. Tool exposure is
filtered by the user's Settings → MCP scope toggles; auth is a bearer token
stored in the OS keychain (or disabled entirely if `auth_mode == "none"`).

The SSE + POST routes are raw ASGI endpoints (mounted in `laya.main` via
`register_mcp_transport`) because `SseServerTransport` needs direct access to
the ASGI `scope`/`receive`/`send` to keep the long-lived stream open. The
remaining management endpoints (`/mcp/config`, `/mcp/token/*`) use the standard
FastAPI router below.
"""

from __future__ import annotations

import hmac
import secrets

import structlog
from fastapi import APIRouter, FastAPI, HTTPException, status
from pydantic import BaseModel
from starlette.requests import Request
from starlette.responses import JSONResponse, Response
from starlette.routing import Mount
from starlette.types import Receive, Scope, Send

from laya.config import load_settings, save_settings
from laya.mcp.http_server import (
    SSE_MESSAGES_PATH,
    build_mcp_server,
    current_space_id,
    sse_transport,
    streamable_sessions,
)
from laya.security.keychain import (
    delete_mcp_token,
    get_mcp_token,
    store_mcp_token,
)

log = structlog.get_logger()

router = APIRouter()

TOKEN_PREFIX = "lyat_"
TOKEN_DISPLAY_PREFIX_LEN = 9  # e.g. "lyat_8f4c"


def _generate_token() -> str:
    return f"{TOKEN_PREFIX}{secrets.token_urlsafe(32)}"


def _auth_mode() -> str:
    return (load_settings().get("mcp", {}) or {}).get("auth_mode", "bearer")


def _check_bearer(auth_header: str | None) -> bool:
    """Return True if the request is authorized to use the MCP transport.

    When `auth_mode == "none"`, always True (loopback bind is the only guard).
    When `auth_mode == "bearer"`, the header must carry the exact stored token,
    compared with `hmac.compare_digest` to avoid timing leaks.
    """
    if _auth_mode() == "none":
        return True

    expected = get_mcp_token()
    if not expected:
        return False
    if not auth_header or not auth_header.lower().startswith("bearer "):
        return False
    presented = auth_header[7:].strip()
    return hmac.compare_digest(presented, expected)


def ensure_startup_token() -> None:
    """Generate and persist an MCP bearer token on engine startup if none exists.

    Called from the FastAPI startup hook so the SSE endpoint is usable
    immediately after install — the user only needs to visit Settings → MCP to
    copy the token into their client.
    """
    if _auth_mode() != "bearer":
        return
    if get_mcp_token() is None:
        token = _generate_token()
        store_mcp_token(token)
        log.info("mcp_token_autogenerated")


# ---------------------------------------------------------------------------
# Raw ASGI routes for the SSE transport
# ---------------------------------------------------------------------------

_server = build_mcp_server()


async def _sse_endpoint(request: Request) -> Response:
    """Handler for `GET /mcp/sse`.

    Authenticates the request, captures the optional `space_id` query param
    into a request-scoped contextvar (inherited by SDK child tasks the MCP
    server spawns), then hands control to `SseServerTransport` for the
    lifetime of the stream. Returns an empty Response only after the stream
    closes — `connect_sse` has already streamed all response bytes by then.
    """
    if not _check_bearer(request.headers.get("authorization")):
        return JSONResponse({"detail": "unauthorized"}, status_code=401)

    space_id = request.query_params.get("space_id") or None
    token = current_space_id.set(space_id)
    try:
        # `request._send` is intentional: SseServerTransport writes SSE frames
        # directly to the ASGI send channel. This is the pattern the official
        # MCP SDK examples use for Starlette/FastAPI integration.
        async with sse_transport.connect_sse(
            request.scope, request.receive, request._send  # type: ignore[attr-defined]
        ) as (read_stream, write_stream):
            await _server.run(
                read_stream,
                write_stream,
                _server.create_initialization_options(),
            )
    finally:
        current_space_id.reset(token)

    return Response()


async def _messages_asgi_app(scope: Scope, receive: Receive, send: Send) -> None:
    """Raw ASGI app for POSTs to `/mcp/messages/...`.

    Mounted (not Route-wrapped) because `SseServerTransport.handle_post_message`
    writes the full HTTP response itself — wrapping it in a Starlette Route
    would cause a double `http.response.start` send.
    """
    if scope["type"] != "http":
        return

    # Extract Authorization header from raw ASGI scope.
    auth_header: str | None = None
    for key, val in scope.get("headers", []):
        if key == b"authorization":
            auth_header = val.decode("latin-1")
            break

    if not _check_bearer(auth_header):
        await JSONResponse({"detail": "unauthorized"}, status_code=401)(scope, receive, send)
        return

    await sse_transport.handle_post_message(scope, receive, send)


MCP_SESSION_ID_HEADER = "mcp-session-id"


async def _streamable_http_app(scope: Scope, receive: Receive, send: Send) -> None:
    """Raw ASGI app for the Streamable HTTP transport at ``/mcp/``.

    Handles POST (JSON-RPC), GET (SSE stream), and DELETE (session teardown).
    New sessions are created on ``initialize`` POSTs (no session header);
    subsequent requests are routed by ``mcp-session-id``.
    """
    if scope["type"] != "http":
        return

    auth_header: str | None = None
    for key, val in scope.get("headers", []):
        if key == b"authorization":
            auth_header = val.decode("latin-1")
            break

    if not _check_bearer(auth_header):
        await JSONResponse({"detail": "unauthorized"}, status_code=401)(scope, receive, send)
        return

    request = Request(scope, receive)
    session_id = request.headers.get(MCP_SESSION_ID_HEADER)

    if session_id:
        session = streamable_sessions.get(session_id)
        if session is None:
            await JSONResponse(
                {"detail": "session not found"}, status_code=404
            )(scope, receive, send)
            return
        await session.transport.handle_request(scope, receive, send)
        return

    # No session header — must be an initialize POST.  Create a new session.
    if request.method != "POST":
        await JSONResponse(
            {"detail": "missing mcp-session-id header"}, status_code=400
        )(scope, receive, send)
        return

    space_id = request.query_params.get("space_id") or None
    session = await streamable_sessions.create_session(space_id=space_id)
    await session.transport.handle_request(scope, receive, send)


def register_mcp_transport(app: FastAPI) -> None:
    """Mount MCP transports on the FastAPI app.

    Order matters — Starlette checks routes sequentially, and the ``/mcp``
    Mount prefix-matches everything under ``/mcp/*``.  Legacy routes must be
    registered first so they match before the catch-all Mount.

    - ``/mcp/sse``         — Legacy SSE (kept for the coding-agent spawner)
    - ``/mcp/messages/``   — Legacy SSE POST receiver
    - ``/mcp/``            — Streamable HTTP (current, used by Claude Desktop)
    """
    # Legacy SSE transport (register first — more specific paths)
    app.add_route("/mcp/sse", _sse_endpoint, methods=["GET"])
    app.router.routes.append(Mount(SSE_MESSAGES_PATH, app=_messages_asgi_app))

    # Streamable HTTP — single Mount handles POST/GET/DELETE
    app.router.routes.append(Mount("/mcp", app=_streamable_http_app))


# ---------------------------------------------------------------------------
# Management endpoints (loopback-trusted; no MCP bearer required)
# ---------------------------------------------------------------------------


class ToolScopes(BaseModel):
    read: bool
    write: bool
    egress: bool


class ExternalServerConfig(BaseModel):
    """Config for a non-Laya STDIO MCP server spawned alongside the built-in
    HTTP/SSE server for in-app coding agents (see agents/mcp_config.py)."""

    enabled: bool
    command: str = ""


class ExternalServers(BaseModel):
    codeidx: ExternalServerConfig = ExternalServerConfig(enabled=False, command="")


class McpConfigResponse(BaseModel):
    tool_scopes: ToolScopes
    auth_mode: str  # "bearer" | "none"
    has_token: bool
    token_prefix: str | None
    url: str
    sse_url: str
    external_servers: ExternalServers


class McpConfigUpdate(BaseModel):
    tool_scopes: ToolScopes | None = None
    auth_mode: str | None = None  # "bearer" | "none"
    external_servers: ExternalServers | None = None


class TokenResponse(BaseModel):
    token: str


def _token_prefix() -> str | None:
    tok = get_mcp_token()
    if not tok:
        return None
    return tok[:TOKEN_DISPLAY_PREFIX_LEN]


def _build_config_response() -> McpConfigResponse:
    settings = load_settings()
    mcp = settings.get("mcp", {}) or {}
    scopes = mcp.get("tool_scopes", {}) or {}
    external = mcp.get("external_servers", {}) or {}
    codeidx = external.get("codeidx", {}) or {}
    from laya.config import ENGINE_HOST, ENGINE_PORT

    return McpConfigResponse(
        tool_scopes=ToolScopes(
            read=bool(scopes.get("read", False)),
            write=bool(scopes.get("write", False)),
            egress=bool(scopes.get("egress", False)),
        ),
        auth_mode=mcp.get("auth_mode", "bearer"),
        has_token=get_mcp_token() is not None,
        token_prefix=_token_prefix(),
        url=f"http://{ENGINE_HOST}:{ENGINE_PORT}/mcp/",
        sse_url=f"http://{ENGINE_HOST}:{ENGINE_PORT}/mcp/sse",
        external_servers=ExternalServers(
            codeidx=ExternalServerConfig(
                enabled=bool(codeidx.get("enabled", False)),
                command=str(codeidx.get("command", "") or ""),
            )
        ),
    )


@router.get("/mcp/config", response_model=McpConfigResponse)
async def get_mcp_config() -> McpConfigResponse:
    """Return current MCP scope toggles, auth mode, and token status."""
    return _build_config_response()


@router.put("/mcp/config", response_model=McpConfigResponse)
async def update_mcp_config(body: McpConfigUpdate) -> McpConfigResponse:
    """Update MCP scopes and/or auth mode. Auto-generates a bearer token when
    switching to `bearer` mode if none exists yet."""
    settings = load_settings()
    mcp = dict(settings.get("mcp", {}) or {})

    if body.tool_scopes is not None:
        mcp["tool_scopes"] = body.tool_scopes.model_dump()

    if body.auth_mode is not None:
        if body.auth_mode not in ("bearer", "none"):
            raise HTTPException(status.HTTP_400_BAD_REQUEST, "auth_mode must be 'bearer' or 'none'")
        mcp["auth_mode"] = body.auth_mode
        if body.auth_mode == "bearer" and get_mcp_token() is None:
            store_mcp_token(_generate_token())

    if body.external_servers is not None:
        command = body.external_servers.codeidx.command.strip()
        if body.external_servers.codeidx.enabled and not command:
            raise HTTPException(
                status.HTTP_400_BAD_REQUEST,
                "codeidx.command is required when codeidx is enabled",
            )
        mcp["external_servers"] = {
            "codeidx": {
                "enabled": body.external_servers.codeidx.enabled,
                "command": command,
            }
        }

    settings["mcp"] = mcp
    save_settings(settings)
    log.info("mcp_config_updated", scopes=mcp.get("tool_scopes"), auth_mode=mcp.get("auth_mode"))
    return _build_config_response()


# Origins the in-app UI / bundled webview legitimately calls from. A browser
# cannot forge the Origin header, and non-browser callers (n8n, curl, the ASGI
# test client) omit it — so an Origin that is present but not in this set is a
# cross-site (CSRF) attempt against a state-changing token endpoint (review §6).
_ALLOWED_ORIGINS = {
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "tauri://localhost",
    "http://tauri.localhost",
    "https://tauri.localhost",
}


def _reject_cross_site(request: Request) -> None:
    origin = request.headers.get("origin")
    if origin and origin not in _ALLOWED_ORIGINS:
        log.warning("mcp_token_cross_site_blocked", origin=origin, path=str(request.url.path))
        raise HTTPException(status.HTTP_403_FORBIDDEN, "cross-site origin not allowed")


@router.post("/mcp/token/refresh", response_model=TokenResponse)
async def refresh_mcp_token(request: Request) -> TokenResponse:
    """Rotate the bearer token. Old token is immediately invalid."""
    # Guard against a body-less cross-site POST rotating the token (review §6).
    _reject_cross_site(request)
    token = _generate_token()
    store_mcp_token(token)
    log.info("mcp_token_rotated")
    return TokenResponse(token=token)


@router.get("/mcp/token/reveal", response_model=TokenResponse)
async def reveal_mcp_token() -> TokenResponse:
    """Return the full current token. Loopback-trusted; same boundary as
    the existing `/settings/api-key/*` endpoints."""
    token = get_mcp_token()
    if not token:
        raise HTTPException(status.HTTP_404_NOT_FOUND, "no MCP token configured")
    return TokenResponse(token=token)


@router.delete("/mcp/token")
async def delete_token(request: Request) -> dict[str, str]:
    """Remove the bearer token. If `auth_mode=bearer`, all MCP requests will
    return 401 until a new token is generated (e.g. via PUT /mcp/config)."""
    _reject_cross_site(request)
    delete_mcp_token()
    return {"status": "deleted"}
